# yaml-language-server: $schema=https://raw.githubusercontent.com/trivoallan/regis/main/regis/schemas/playbook/v1alpha1/playbook.schema.json
apiVersion: regis.trivoallan.dev/v1alpha1
kind: Playbook
metadata:
  name: "{{ cookiecutter.project_slug }}"
  title: "{{ cookiecutter.project_name }}"
  description: "{{ cookiecutter.description }}"
  labels:
    app.kubernetes.io/version: "1.0.0"
spec:
  tiers:
    - name: Gold
      condition:
        ">": [{ var: rules_summary.score }, 90]
    - name: Silver
      condition:
        ">": [{ var: rules_summary.score }, 70]
    - name: Bronze
      condition:
        ">": [{ var: rules_summary.score }, 50]
  rules:
    - provider: cve
      rule: cve-count
      slug: cve-critical
      level: critical
      options:
        level: critical
        max_count: 0
    - provider: sbom
      rule: has-sbom
      slug: has-sbom
      level: warning
